// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonusIdrici2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250723144153_FixReportNumeroComponentiType")]
    partial class FixReportNumeroComponentiType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Ente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cap");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("CodiceFiscale");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provincia");

                    b.Property<string>("Regione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("regione");

                    b.Property<string>("istat")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("istat");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("partitaIva")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("patitaIVA");

                    b.HasKey("id");

                    b.ToTable("enti", (string)null);
                });

            modelBuilder.Entity("Models.Report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdEnte")
                        .HasColumnType("int")
                        .HasColumnName("id_ente");

                    b.Property<string>("annoValidita")
                        .HasColumnType("longtext")
                        .HasColumnName("anno_validita");

                    b.Property<string>("capAbitazione")
                        .HasColumnType("longtext")
                        .HasColumnName("cap_abitazione");

                    b.Property<string>("codiceBonus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codice_bonus");

                    b.Property<string>("codiceFiscale")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codice_fiscale");

                    b.Property<string>("cognomeDichiarante")
                        .HasColumnType("longtext")
                        .HasColumnName("cognome_dichiarante");

                    b.Property<DateTime?>("dataCreazione")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_creazione");

                    b.Property<DateTime>("dataFineValidita")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_fine_validita");

                    b.Property<DateTime>("dataInizioValidita")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inizio_validita");

                    b.Property<string>("esito")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("esito");

                    b.Property<string>("esitoStr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("esito_str");

                    b.Property<string>("idAto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("idAto");

                    b.Property<int?>("idFornitura")
                        .HasColumnType("int")
                        .HasColumnName("idFornitura");

                    b.Property<string>("indirizzoAbitazione")
                        .HasColumnType("longtext")
                        .HasColumnName("indirizzo_abitazione");

                    b.Property<string>("istat")
                        .HasColumnType("longtext")
                        .HasColumnName("istat");

                    b.Property<string>("nomeDichiarante")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_dichiarante");

                    b.Property<string>("numeroCivico")
                        .HasColumnType("longtext")
                        .HasColumnName("numero_civico");

                    b.Property<int?>("numeroComponenti")
                        .HasColumnType("int")
                        .HasColumnName("numero_componenti");

                    b.Property<string>("presenzaPod")
                        .HasColumnType("longtext")
                        .HasColumnName("presenza_pod");

                    b.Property<string>("provinciaAbitazione")
                        .HasColumnType("longtext")
                        .HasColumnName("provincia_abitazione");

                    b.HasKey("id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Models.UtenzaIdrica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdEnte")
                        .HasColumnType("int")
                        .HasColumnName("id_ente");

                    b.Property<string>("codiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("codice_fiscale");

                    b.Property<string>("cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cognome");

                    b.Property<string>("idAcquedotto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("idAcquedotto");

                    b.Property<string>("indirizzoUbicazione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("indirizzo_ubicazione");

                    b.Property<string>("interno")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("interno");

                    b.Property<string>("matricolaContatore")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("matricola_contatore");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("numeroCivico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero_civico");

                    b.Property<DateTime?>("periodoFinale")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("periodo_finale");

                    b.Property<DateTime?>("periodoIniziale")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("periodo_iniziale");

                    b.Property<string>("piano")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("piano");

                    b.Property<string>("scalaUbicazione")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("scala_ubicazione");

                    b.Property<int>("stato")
                        .HasColumnType("int")
                        .HasColumnName("stato");

                    b.Property<string>("subUbicazione")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sub_ubicazione");

                    b.Property<string>("tipoUtenza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_utenza");

                    b.HasKey("id");

                    b.ToTable("utenzeidriche", (string)null);
                });

            modelBuilder.Entity("Dichiarante.Dichiarante", b =>
                {
                    b.Property<int>("IdDichiarante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CodiceFamiglia")
                        .HasColumnType("int")
                        .HasColumnName("CodiceFamiglia");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("codiceFiscale");

                    b.Property<string>("CodiceFiscaleIntestatarioScheda")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("CodiceFiscaleIntestatarioScheda");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasColumnName("cognome");

                    b.Property<string>("ComuneNascita")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ComuneNascita");

                    b.Property<string>("DataNascita")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dataNascita");

                    b.Property<string>("IndirizzoResidenza")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IndirizzoResidenza");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeEnte")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NomeEnte");

                    b.Property<string>("NumeroCivico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NumeroCivico");

                    b.Property<int>("NumeroComponenti")
                        .HasColumnType("int")
                        .HasColumnName("NumeroComponenti");

                    b.Property<string>("Parentela")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Parentela");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Sesso");

                    b.HasKey("IdDichiarante");

                    b.ToTable("dichiaranti", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
