// <auto-generated />
using BonusIdrici2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonusIdrici2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721095627_FixDichiaranteColumnType2")]
    partial class FixDichiaranteColumnType2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BonusIdrici2.Models.Ente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cap")
                        .HasColumnType("longtext");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("longtext");

                    b.Property<string>("Provincia")
                        .HasColumnType("longtext");

                    b.Property<string>("Regione")
                        .HasColumnType("longtext");

                    b.Property<string>("istat")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("enti", (string)null);
                });

            modelBuilder.Entity("BonusIdrici2.Models.UtenzaIdrica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdEnte")
                        .HasColumnType("int")
                        .HasColumnName("id_ente");

                    b.Property<string>("codiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("codice_fiscale");

                    b.Property<string>("cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cognome");

                    b.Property<string>("idAcquedotto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("idAcquedotto");

                    b.Property<string>("indirizzoUbicazione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("indirizzo_ubicazione");

                    b.Property<string>("interno")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("interno");

                    b.Property<string>("matricolaContatore")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("matricola_contatore");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("numeroCivico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero_civico");

                    b.Property<string>("periodoFinale")
                        .HasColumnType("longtext")
                        .HasColumnName("periodo_finale");

                    b.Property<string>("periodoIniziale")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("periodo_iniziale");

                    b.Property<string>("piano")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("piano");

                    b.Property<string>("scalaUbicazione")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("scala_ubicazione");

                    b.Property<int>("stato")
                        .HasColumnType("int")
                        .HasColumnName("stato");

                    b.Property<string>("subUbicazione")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sub_ubicazione");

                    b.Property<string>("tipoUtenza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_utenza");

                    b.HasKey("id");

                    b.ToTable("utenzeidriche", (string)null);
                });

            modelBuilder.Entity("Dichiarante.Dichiarante", b =>
                {
                    b.Property<int>("IdDichiarante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodiceFamiglia")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CodiceFamiglia");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("codiceFiscale");

                    b.Property<string>("CodiceFiscaleIntestatarioScheda")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CodiceFiscaleIntestatarioScheda");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cognome");

                    b.Property<string>("ComuneNascita")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ComuneNascita");

                    b.Property<string>("DataNascita")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dataNascita");

                    b.Property<string>("IndirizzoResidenza")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IndirizzoResidenza");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeEnte")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NomeEnte");

                    b.Property<string>("NumeroCivico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NumeroCivico");

                    b.Property<string>("NumeroComponenti")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NumeroComponenti");

                    b.Property<string>("Parentela")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Parentela");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Sesso");

                    b.HasKey("IdDichiarante");

                    b.ToTable("dichiaranti", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
