// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonusIdrici2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250716091858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Ente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cap")
                        .HasColumnType("longtext");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("longtext");

                    b.Property<string>("Provincia")
                        .HasColumnType("longtext");

                    b.Property<string>("Regione")
                        .HasColumnType("longtext");

                    b.Property<string>("istat")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Enti");
                });

            modelBuilder.Entity("Dichiarante.Dichiarante", b =>
                {
                    b.Property<int>("IdDichiarante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodiceFamiglia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodiceFiscaleIntestatarioScheda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComuneNascita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataNascita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IndirizzoResidenza")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeEnte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCivico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroComponenti")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Parentela")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdDichiarante");

                    b.ToTable("Dichiaranti");
                });
#pragma warning restore 612, 618
        }
    }
}
